spring.application.name=journalApp
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb

#if you use authentication then you have to use -
#spring.data.mongodb.username=username
#spring.data.mongodb.password=mypassword
